# Generated by Django 5.1.5 on 2025-01-28 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970)]),
        ),
    ]
